### ISSUE TITLE
Alpine linux?

### ISSUE THREAD

**Issue by pierreozoux** [Sing-Li/meteor#1]
Did you think about alpine linux to make even smaller?

I didn't try it myself yet, but I'm curious. Just sharing some knowledge here:
https://github.com/paz-sh/paz-base

Cheers!

**Comment by Sing-Li** [comment]
@pierreozoux   Thanks for sharing!   Will take a look.

**Comment by Sing-Li** [comment]
@pierreozoux 

OK ... the alpine base is bug-city and sent me down a rabbit hole  .....

But now I'm back up with this !!  ... https://registry.hub.docker.com/u/singli/meteorslim/   :-)

Experimental, proceed with caution.

**Comment by pierreozoux** [comment]
Hehe :)

I was playing around yesterday, noticed some bugs also. Alpine is not straight forward :/

I didn't find the Dockerimage, I'm curious to see how you did manage!

**Comment by Sing-Li** [comment]
Had to go back in history .... alpine before musl  - basically based on busybox - people worked long and hard to get glibc covered and wrapped back then.   Seems like musl is going through it all over again.  Just emailed the dockerfile to you.

**Comment by pierreozoux** [comment]
Ok thanks, but I don't understand why you don't put it as a branch of this repo? I'll have more time next week to try it on :)

Cheers!

**Comment by Sing-Li** [comment]
Two different and independent stream of tuning :)    Currently I do not yet understand the run-time characteristics and limitations of this super-slim stream - needs a lot more experimentation.  

And to tune the other from-stable but 'fatter' stream down to this size, will probably take months - if not years of part-time tinkering.

**Comment by pierreozoux** [comment]
Ok, got it :)
